import Banner from "../components/Banner";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Bannersquare from "../components/Bannersquare";
import Testimonial from "../components/Testimonial";
import Foursquare from "../components/Foursquare";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Midas Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <div className="container center-info">
        <div className="container info-text">
        <h2>It’s a Data-Driven Fact:</h2>
        <h5>Midas is a staffing agency that delivers better candidates and better career opportunities. Ready to get started?</h5>
        </div>
        <a className="info-link" href="https://www.midashealthcare.com/" >More About Medix ›</a>
      </div>
      <Bannersquare />
      <Testimonial />
      <Foursquare/>
      <Footer/>
    </>
  );
}
